openapi: 3.0.0
info:
  title: Petshop Api
  description: Restful APi for a petshop
  version: 0.1.9

servers:
  - url: http://localhost:8000/api/v1
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /users/login:
    post:
      summary: User Login 
      responses:
        '200': 
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string